### ISSUE TITLE
Home Assistant Setup

### ISSUE THREAD

**Issue by nimdy2017** [AntoineGS/teams-status-rs#13]
Do you have any guidance on how the Home Assistant set up is done? I've added my HASS URL and created a long lived token, but nothing happens in the HASS from what I can see. Should I be creating a webhook URL and point the utility to that? I've also noticed when the application restarts the long live token changes. Is that correct?

**Comment by AntoineGS** [comment]
The tokens and passwords do get encrypted so as not to save them to the text file as plain text, they will start with `en//` once encoded so that is normal. 
Using a long-live is the correct way!
A couple of things you can verify/try:
- In the configuration, make sure your URL includes the port if you typically access it in your browser by including the port (like `http://192.168.1.10:8123`).
- Check the logs in the folder where you are running the application from, it is named `output.log`, it might hold some information as to why it is not working.
- You can download Postman and attempt to connect to your HA by pasting the URL (port included) and add `/api/` at the end. From the example above, it would be `http://192.168.1.10.8123/api/`. You should get a `401: Unauthorized` error (not a 404 or other error). This will more or less confirm that you have the URL correct.

Let me know if that helps, if not I can try and find other things to check!

**Comment by nimdy2017** [comment]
Thank you. All working now. I set it up alongside the original script so didn't notice the new entities appear amongst the ones for the 'old Teams'. Works really well. Thanks for your sharing your work.

**Comment by AntoineGS** [comment]
🙂 Glad to hear it is working!
