### ISSUE TITLE
How to install this plugin

### ISSUE THREAD

**Issue by BernieV1977** [AntoineGS/teams-status-rs#17]
Hi, I can't find out how to install your teams-status-rs for using with HA.
Can you give some additional tips?
Thx

**Comment by AntoineGS** [comment]
It is worth nothing that this is an application that runs on Windows on the same machine that runs Teams, that might be a source of confusion as I do not mention it explicitly in the readme.

**Comment by BernieV1977** [comment]
Thx. My fault not thinking about it...

**Comment by ron-osu** [comment]
+1 for the original Issue.  

The instructions start with "Launch the application".  What application?  I don't see an EXE file.  

Where do I launch this application?  (I know this answer because of this Issue thread, but instructions don't mention that.)

I am a quasi-developer (mostly PowerShell nowadays but C++ back in the day) but have never worked with Rust.  I spent two hours trying to install the Rust dependencies (there are quite a few) and still got an error (below) trying to execute your project.  Probably user error / lack of Rust knowledge.

cargo run / cargo build returned the following:
failed to read `C:\Users\Ron\Downloads\teams-status-rs-master\home-assistant-rest\Cargo.toml`

I really appreciate your efforts and the code MIGHT be outstanding, but few will ever find out.  The documentation isn't useful to get anyone off the ground who hasn't used Rust on Windows before.   I'm sure I could figure it out with enough research, but my goal was to publish my Teams Status into Home Assistant, not to become a Rust expert or install a ton of dependencies.

It's also not clear from the documentation how this is functioning - Is it using the Teams log files?  Teams client API?  Both?

**Comment by AntoineGS** [comment]
The compiled application can be found in the releases sections, no need to know or install rust to use this ;) :
https://github.com/AntoineGS/teams-status-rs/releases

As for the connection method, it uses the WebSocket API, I have tried on a few occasions to add additional data points using the log file but it was not fast/accurate enough for my liking.

If you would like to add some notes in the Readme.md for the next person I will gladly review/merge a PR for it, they are always welcomed!
